### PR TITLE
Move frontend to yew framework

### PR DESCRIPTION
**Pull request by tarkah**

### CODE REVIEW

**Comment by tarkah** [comment]
@maxjoehnk Check it out!

I've added the "frontend" folder.

- You can `npm install` -> `npm run start:dev` for a dev server... `/api` routes are proxied to port 8080, so you can run the program in the background with an active API and get live reloading and all that fun stuff on the frontend.
- `npm run build` will automatically publish all files to `embed/static` and get embedded into the program when you build it.

So now the program only serves those static files, wasm and the `/api` endpoints. I've also made sure that all requests that aren't `/` get served `index.html` so the whole single page app thing works nicely.

Everything is working except for table sorting and toast notification, but this shouldn't be too hard. I haven't applied any of your styling yet... css is my enemy so if you want to take a stab, that'd be great!

**Comment by tarkah** [comment]
There is definitely a resource leak going on, I believe it's related to the Router. When the route is changed and a new component is rendered, the old component isn't being destroyed properly, I suspect. There is an issue for this on Yew that I am tracking, hopefully it's fixed soon. 

Relates to these warnings in console when you change routes

```
WARN:yew::agent -- The Id of the handler: 0, while present in the slab, is not associated with a callback.
WARN:yew::virtual_dom::vtag -- Node not found to remove VTag
```

**Comment by tarkah** [comment]
I've applied your styling! All classes have been associated correctly and your style.css is being used.

I still need to do sorting and toasts. I'll work on creating a toast container in yew that I can send messages to from each page once fetch operations are completed.

For sorting, since we are doing pagination and searching against the server, I'll have a new sort parameter added to the api request, which will be set by clicking on the sortable column headers in the table.

**Comment by maxjoehnk** [comment]
I haven't really looked into the code yet, but is there a reason why you're including the compiled output in the repository?
If you don't wanna depend on frontend tooling (e.g. webpack) we can maybe look for something else. There are multiple bundlers written in rust, not sure whether there is a wasm compatible one yet though.

* https://packem.github.io/
* https://pax.js.org/

Or maybe we could just skip a bundler all together:
https://rustwasm.github.io/docs/wasm-bindgen/examples/without-a-bundler.html

**Comment by tarkah** [comment]
Yeah I was thinking about this briefly, but I don't really know what's best practice currently. I'd imagine just including a build.rs or something could work fine.

My web dev experience is super minimal, but I've used webpack previously and yew had a template for working with it. I definitely liked having it there at minimum for development.

But I agree, I shouldn't be including the compiled wasm / bundled js in the repository, I'll need to find a good way to have it build with everything else. Thanks for the suggestions!

**Comment by tarkah** [comment]
The more I think about it, the more I don't want those dependencies on frontend tooling.

At first I was just using cargo-web and it mostly worked. The one issue being it doesn't support serving index.html on 404s with it's dev server. But I can deal with that by just refreshing the page to '/'.

**Comment by tarkah** [comment]
@maxjoehnk I've got everything where I want it, so I am going to go ahead and merge this. I've updated the styling a little bit so there are some breakpoints / padding on wider screens.

I'm still using webpack, but I've updated the azure pipelines CI to build the frontend prior to building the program, so I was able to remove the compiled frontend from the repo. Thanks for your help!

**Pull request merged**
