### PR TITLE
Remove Bootstrap/jQuery dependencies

### PR DESCRIPTION
**Pull request by maxjoehnk**
I've removed the bootstrap and jquery dependencies as I wanted to use this software last weekend but couldn't properly use the web frontend as I had no internet connection at the venue.
While doing this I've redesigned the web interface without removing functionality.
(Only thing I've removed is the paging size selector. I can add it back if you want.)

Screenshots of new Interface:
image
image
image
image
image

### CODE REVIEW

**Comment by maxjoehnk** [comment]
Totally forgot the sorting function, gonna implement this tomorrow.

**Comment by tarkah** [comment]
Hey! Thanks for the pull request. I completely agree that is should work offline.

I haven't tested it yet, but once I confirm it looks good from my phone and browser, and you add the sorting, I'll definitely merge.

If you're interested... I have a branch `web-player` that I haven't finished up yet, but it loads WASM to play back the song in the browser and communicates with websockets. It works pretty good, I just haven't finished the necessary synchronization commands for when "next" and "stop" are used from the queue page. The idea was to host this thing at my house, with the site available over the Internet. And you could load up `/player` on whatever you device wanted to play back without the need to transport anything. I need to finish that, I've been side tracked with other projects.

**Comment by maxjoehnk** [comment]
Sorting is implemented.

Yeah, I've seen the web-player branch. Haven't really looked into it yet but I will check it out later.

**Comment by tarkah** [comment]
Just tested this out on web and mobile, looks pretty good! However, filtering doesn't work properly, it only filters what's showing on the current page of the table, not across the entire table contents. Also, the background image resizes when my keyboard opens / closes. Is there a way to keep this from happening?

For some reason on mobile, the table isn't paginated on the songs tab. This is probably because I have like 10k+ songs and things just break with that much data.

This is a bigger issue that probably needs to be fixed down the road. Loading so much song data isn't ideal with a big collection. Pagination and filtering should be handled by the server so a reasonable amount of records are returned and the thing is usable when collection size gets big.

**Comment by tarkah** [comment]
Maybe using something like [https://github.com/tantivy-search/tantivy](https://github.com/tantivy-search/tantivy) for indexing the collection so filtering can be responsive

**Comment by maxjoehnk** [comment]
Oh dang, I've done a real stupid mistake with the filtering.
Actually it should still paginate, but maybe you can't see the paging because of some sizing issues.
I'll check it on my phone.

Yeah, server side filtering would be way better, but I didn't want to introduce additional major changes.
I would also like to add a now playing info in the upper right corner later on.

**Comment by maxjoehnk** [comment]
I'm not sure whether I can fix the jumping background issue without just setting a fixed height of the background image (which feels kinda hacky).
Another solution would be to get the size on startup and fix it for the background image. But this would either not work on tablets or break on manual resizing of the browser window.

**Comment by tarkah** [comment]
No worries on the background.

So here are my thoughts, I can add a few additional API endpoints:

I'll add `/api/songs` and `/api/artists` which return an object with `page` and `total pages` , then the data nested under a `data` field.  These endpoints will take 2 parameters, `page` and `query`.  Query param will be used for filtering, the collection will be indexed using tantivy so it should respond very quickly.  I'll also include `/api/now` which will return song and artist of current song. 

I'll remove the templating from the songs and artists html pages so the tables are no longer generated server side. We need some javascript added to dynamically update tables from querying those endpoints on page load, when page selection is made, or when typing in the filter bar.  Is this something you can help with?

**Comment by maxjoehnk** [comment]
Yeah, sounds good.
Do you want to do this in this PR or in a separate one?

**Comment by maxjoehnk** [comment]
Also, do you have an opinion regarding js frameworks? 
I've tried to use js just for enhancements (even thought about using forms for play/add to queue) but this would not work without server side rendering. I don't think thats a big deal personally but maybe your opinion differs?

**Comment by tarkah** [comment]
Here is fine. Let me see if I can push out those endpoints today. I probably won't be able to get pagination or filtering functionality added until next week once I have some time off. But at least those endpoints will be active to build the front end against.

I've used Vue before, I don't really think we need a framework for this though. Just some simple fetch functions that update the tables with the returned data.

**Comment by maxjoehnk** [comment]
Alright. Is there something I can help you with on the backend side?

I was actually thinking of something like [lit-html](https://lit-html.polymer-project.org/), as the raw templating code can get quite cumbersome.

**Comment by tarkah** [comment]
So checkout the commit I just published.  I added the two api endpoints, right now they return all the records. The artists and songs pages now don't return anything.

I think once I setup indexing, the response data will be in a slightly different format, and the artists response wont need to include the songs. I can add an `artist` parameter to `/api/songs` which we can call when the artist page is loaded.

I'm not exactly sure what you mean in your latest response. I am confused where templating will still need to come into play?

**Comment by maxjoehnk** [comment]
Allright, that does look good.

I was talking about the templates for the rows, as I would've removed them from the html templates.
But for now we should be fine. I'll add the loading tomorrow. Is there a reason why you've used a map in the response instead of a Vec?

**Comment by tarkah** [comment]
The reason it's stored as a HashMap server side was purely for the ease of pulling out the specific song or artist by their hash. I'm just returning that object.

I agree the response should return an array. I can make this transformation happen, ensuring the resulting array is sorted by song / artist name, or if filter is used, by the match score.

**Comment by tarkah** [comment]
Ok, check it out now, is that response more appropriate?

**Comment by tarkah** [comment]
Omg, I have an `artist_id` parameter working on `/api/songs` where it'll just return the songs of that artist. However, I am running into the weirdest bug that I can't figure it out. `artist_id` is a u64. For some reason, it's being serialized incorrectly. For example, an artists value is actually `10904881404067408254`, but it is returning as `10904881404067408000` in the response, and therefore when you try to use that id in the parameter, it doesn't return any songs. I feel like I am taking crazy pills, I have no idea why these u64 values aren't serializing correctly, I can't find anything online that suggests there is some issue there.

I'll push this commit, can you test on your end? Can you double check on a decent sample of songs that the returned artist_id works as a parameter, and if not, that you are seeing the same serialization issue where it's being rounded down?

**Comment by tarkah** [comment]
Just added paging functionality, it'll return an error if page is specified as 0 or past the last page.

**Comment by tarkah** [comment]
I've added very basic filtering, in that as long as the lowercase name of song and / or artist contains the lowercase string being used, it'll return a result.

I honestly think this is fine for the purposes of this program. I don't think we need anything fancy / indexed with scoring to fit the bill here.

**Comment by tarkah** [comment]
@maxjoehnk Not sure if you have had time to work on this at all, but I have started porting this over to a new frontend using [https://github.com/yewstack/yew](https://github.com/yewstack/yew). Was a good excuse to learn that framework and allows me to avoid javascript at all costs.

I'll hopefully have something I can push out in the next couple weeks. Just wanted to let you know so you don't sink any time on this.

**Comment by maxjoehnk** [comment]
No sorry, I did not had any time yet. But I like the decision to try yew, haven't tried it yet but looks kinda nice.
Maybe we can use the style changes I've done and use yew for more interactivity.
We could also go pure html, at least for queueing/playing tracks and only enhance the tables with yew.

**Comment by tarkah** [comment]
No worries, hope you had a good holiday!

I've pretty much got 100% of the functionality worked out in yew, using the API changes here. Server will just need to host the index file, static files including wasm, then API endpoints.

I just need to iterate a couple more pages then apply your formatting from this PR.

**Comment by tarkah** [comment]
@maxjoehnk Just wanted to follow up with you and say thanks for the front-end design you put together in this PR! I'm sure you saw, but I ended up merging it within migration to the yew frontend. I've added you to the acknowledgements on the README for your contributions here. I really appreciate your help and design.

If you haven't been following, there have been a lot of great additions since moving to yew, which has made it super easy to add features. I've stabilized the web player which works great (even on mobile browsers), added options to customize how the player looks, and added the ability to favorite songs / view favorites. Thanks again!

**Comment by maxjoehnk** [comment]
No problem, glad you like it.
I'm actually using this software once a year, when we have a christmas party in the club i'm part of.
Looks really nice and I'm really happy that I've found this piece of software.
No more VLC remote shenanigans :D

**Pull request closed without merging**
